cat("ML data file summary\n")
cat("-------------------------------------\n")
Sys.sleep(1)
cat("ML file dimensions: \n")
cat("Group labels (size): \n")
cat("\n\n")
cat("SVM modelling with nested cross-valdation\n")
cat("-------------------------------------\n")
Sys.sleep(1)
cat("Total internal cross-validation accuracy: \n")
cat("Final SVM model saved to file: ", paste0("cv_only_", "_final_svm_model.Rdata\n"))
cat("\n\n")
cat("SVM permutation test\n")
cat("-------------------------------------\n")
Sys.sleep(1)
cat("Permutation test results saved to file: svm_m.perm.csv\n")
cat("Permutation plot saved to file: svm_m_perm.svm.perm.plot.pdf\n")
cat("\n\n")
cat("CV: ROC-AUC\n")
cat("-------------------------------------\n")
Sys.sleep(1)
cat("NOTE: Check the SVM results file ", paste0("_svm_results.txt"), " for AUC values.\n")
cat("ROC figure saved to file (check SVM result file for AUC value): svm_m.svm.roc.pdf\n")
cat("\n\n")
cat("Clustering analysis\n")
# cat("PCA on SVM selected pairs\n")
cat("-------------------------------------\n")
Sys.sleep(1)
cat("PCA on CV-SVM-rRF-FS selected features saved to:\n")
Sys.sleep(1)
cat("\tOn all data:\n")
Sys.sleep(1)
cat("\t\tbiplot: pca_svm_rffs_all_samples.pca.biplot.pdf\n")
Sys.sleep(1)
cat("\t\tboxplot: pca_svm_rffs_all_samples.pca.boxplot.pdf\n")
Sys.sleep(1)
cat("\n\n")
cat("Hierarchical clustering on CV-SVM-rRF-FS selected features saved to:\n")
Sys.sleep(1)
cat("\tOn all data:\n")
Sys.sleep(1)
cat("\t\t", paste0("_hclust_nestedcv_all_samples_heatmap.pdf"), "\n")